---
HOSTS:
  redhat5-64-1:
    pe_dir:
    pe_ver:
    pe_upgrade_dir:
    pe_upgrade_ver:
    platform: el-5-x86_64
    packaging_platform: el-5-x86_64
    template: redhat-5-x86_64
    hypervisor: vmpooler
    roles:
    - agent
    - default
CONFIG:
  nfs_server: none
  consoleport: 443
  pooling_api: http://vmpooler.delivery.puppetlabs.net/